language: go
sudo: false
go:
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - 1.7
    - 1.8
    - tip
matrix:
    allow_failures:
        - go: tip
    fast_finish: true

script:
    - cd $HOME/gopath/src/github.com/FeiniuBus/SqlExecutor-Go
    - go build ./dynamicquery
    - go test ./dynamicquery
notifications:
    email: false